services:
  app:
    build: .
    image: docuseal-local
    volumes:
      - ./docuseal:/data/docuseal
    environment:
      - HOST=${HOST:-localhost}
      - FORCE_SSL=${FORCE_SSL:-false}

  caddy:
    image: caddy:latest
    command: caddy reverse-proxy --from ${HOST:-localhost} --to app:3000
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - ./caddy:/data/caddy
    environment:
      - HOST=${HOST:-localhost}
